### PR TITLE
Fix cursor position in terminal mode

### LINKED ISSUE #94: cursor hop in terminal buffers
hi! thanks for making vv, and i'm looking forward to using it! after building on the head of master today (latest macos, npm, and yarn), i started using vv to edit my dotfiles, and i'm a heavy user of the embedded neovim terminal. while in insert mode inside a window with a terminal buffer, the cursor hops around, which can make it tricky to follow what i'm typing. i've attached a video that hopefully shows what i'm talking about:

https://user-images.githubusercontent.com/1655830/113525517-67d1f700-9583-11eb-9cb9-055e7bf0d032.mov

i was using hyper.js prior to vv, which doesn't seem to have this issue. any ideas on where i could start looking around if i wanted to try and fix this myself?

### PR DESCRIPTION
**Pull request by igorgladkoborodov**
Fix cursor position in terminal buffers. For some reason nvim does not send the very last cursor position in terminal buffers after redraw. If you send any command to nvim, it updates the cursor position. Added a temporary workaround, send `getMode` on `flush`. Need to investigate, it looks like a bug in nvim. I will file a ticket if it is.

Fixes #94

### CODE REVIEW

File: packages/browser-renderer/src/screen.ts [hunk 1]
```diff
@@ -562,12 +598,15 @@ const screen = ({
...
-      }
-    }, 1000 / TARGET_FPS),
+    flush: () => {
+      rerenderIfNeeded();
+
+      // Temporary workaround to fix cursor position in terminal mode. Nvim API does not send the very last cursor
+      // position in terminal on redraw, but when you send any command to nvim, it redraws it correctly. Need to
+      // investigate it and find a better permanent fix. Maybe this is a bug in nvim and then
+      // TODO: file a ticket to nvim.
+      nvim.getMode();
```
Comment (igorgladkoborodov) [inline packages/browser-renderer/src/screen.ts:608]: Actual change. Everything else is small refactoring and making TypeScript happy
